export interface KitchenPreset {
  id: string;
  name: string;
  description: string;
  icon: string;
  appliances: string[];
  implements: string[];
}

export const kitchenPresets: KitchenPreset[] = [
  {
    id: 'standard',
    name: 'Standard',
    description: 'Essential appliances and tools for everyday cooking',
    icon: 'home',
    appliances: [
      'Stove/Cooktop',
      'Oven',
      'Microwave',
      'Refrigerator',
      'Freezer',
      'Toaster',
      'Coffee Maker',
    ],
    implements: [
      "Chef's Knife",
      'Paring Knife',
      'Cutting Board',
      'Mixing Bowls',
      'Measuring Cups',
      'Measuring Spoons',
      'Large Pot',
      'Medium Pot',
      'Large Frying Pan/Skillet',
      'Non-stick Pan',
      'Baking Sheet',
      'Spatula',
      'Wooden Spoon',
      'Ladle',
      'Tongs',
      'Whisk',
      'Can Opener',
      'Vegetable Peeler',
      'Colander/Strainer',
    ],
  },
  {
    id: 'hardcore',
    name: 'Hardcore',
    description: 'Complete professional-grade kitchen setup with all the bells and whistles',
    icon: 'flame',
    appliances: [
      'Stove/Cooktop',
      'Oven',
      'Microwave',
      'Refrigerator',
      'Freezer',
      'Toaster',
      'Toaster Oven',
      'Air Fryer',
      'Slow Cooker/Crock Pot',
      'Instant Pot/Pressure Cooker',
      'Rice Cooker',
      'Blender',
      'Food Processor',
      'Stand Mixer',
      'Hand Mixer',
      'Immersion Blender',
      'Electric Kettle',
      'Coffee Maker',
      'Espresso Machine',
      'Waffle Maker',
      'Griddle/Pancake Griddle',
      'Deep Fryer',
      'Sous Vide',
      'Bread Maker',
      'Dehydrator',
    ],
    implements: [
      "Chef's Knife",
      'Paring Knife',
      'Bread Knife',
      'Cutting Board',
      'Mixing Bowls',
      'Measuring Cups',
      'Measuring Spoons',
      'Large Pot',
      'Medium Pot',
      'Small Pot',
      'Large Frying Pan/Skillet',
      'Medium Frying Pan',
      'Non-stick Pan',
      'Cast Iron Skillet',
      'Baking Sheet',
      'Cake Pan',
      'Muffin Tin',
      'Casserole Dish',
      'Roasting Pan',
      'Spatula',
      'Wooden Spoon',
      'Slotted Spoon',
      'Ladle',
      'Tongs',
      'Whisk',
      'Can Opener',
      'Vegetable Peeler',
      'Grater/Zester',
      'Colander/Strainer',
      'Potato Masher',
      'Rolling Pin',
      'Kitchen Scissors',
      'Meat Thermometer',
    ],
  },
  {
    id: 'small',
    name: 'Small',
    description: 'Compact essentials perfect for studio apartments or small spaces',
    icon: 'minimize',
    appliances: [
      'Microwave',
      'Toaster Oven',
      'Electric Kettle',
      'Coffee Maker',
      'Mini Fridge',
    ],
    implements: [
      "Chef's Knife",
      'Paring Knife',
      'Cutting Board',
      'Mixing Bowls',
      'Measuring Cups',
      'Measuring Spoons',
      'Small Pot',
      'Medium Frying Pan',
      'Non-stick Pan',
      'Baking Sheet',
      'Spatula',
      'Wooden Spoon',
      'Can Opener',
      'Vegetable Peeler',
      'Colander/Strainer',
    ],
  },
  {
    id: 'camping',
    name: 'Camping',
    description: 'Portable outdoor cooking gear for camping, cabins, or RVs',
    icon: 'tent',
    appliances: [
      'Portable Propane Stove',
      'Cooler',
      'Portable Grill',
      'Camp Coffee Maker',
    ],
    implements: [
      'Camp Knife',
      'Cutting Board',
      'Camping Pot Set',
      'Cast Iron Skillet',
      'Camping Plates/Bowls',
      'Camping Utensils',
      'Can Opener',
      'Spatula',
      'Tongs',
      'Cooler',
      'Water Bottles',
      'Portable Cutting Board',
    ],
  },
];

export const presetLocationSuggestions: Record<string, string> = {
  standard: 'Main Kitchen',
  hardcore: 'Main Kitchen',
  small: 'Studio Kitchen',
  camping: 'Camping Setup',
};
